academy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('courses:login_page')),  # Redirect root URL to login_page
]

courses/urls.py
from django.urls import path, re_path
from django.shortcuts import redirect
from . import view
from .views.views_students import save_student
from .views.views_teacher import save_teacher, delete_teacher
from .views.view_course import add_course, delete_course
from .views.views_courses import course_detail, register_attendance
from .views.views_coursestudent import add_course_student
from .views.views_user import login_page, user_login, user_logout

app_name = 'courses'
urlpatterns = [
    path('', view.index, name='index'),
    # path('<int:course_id>', view.course_detail, name='course_detail'),
    path('<int:course_id>', course_detail, name='course_detail'),
    path('student/', view.students, name='students'),
    path('save_student/', save_student, name='save_student'),
    path('teacher/', view.teachers, name='teacher'),
    path('save_teacher/', save_teacher, name='save_teacher'),
    path('add_course/', add_course, name='save_course'),
    # path('course/<int:course_id>/', course_detail, name='course_detail'),
    path('<int:course_id>/add_student/', add_course_student, name='add_course_student'),
    path('login/',login_page, name='login_page'),
    path('user_login', user_login, name='user_login'),
    path('logout', user_logout, name='user_logout'),
    path('course/<int:course_id>/delete/', delete_course, name="delete_course"),
    path('<int:teacher_id>/delete/', delete_teacher, name="delete_teacher"),
    path('register-attendance/<int:student_id>/', register_attendance, name='register_attendance'),

    # Catch-all pattern to redirect to login_page
    re_path(r'^.*$', lambda request: redirect('courses:login_page'), name='catch_all'),
]

courses/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=30, default="juan", unique=True)
    ci = models.IntegerField(default=0)
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=200)
    ci = models.IntegerField()
    username = models.CharField(max_length=30, default="juan", unique=True)

    def __str__(self):
        return '{} (CI: {})'.format(self.name, self.ci)

class Course(models.Model):
    name = models.CharField(max_length=200)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(default=timezone.now)
    state = models.CharField(max_length=20, default='Activo') # Activo, Inactivo, Concluido y Anulado
    material_curso = models.CharField(max_length=200, default='libros,web')

    def __str__(self):
        return '{} - {} - {} - {} - {}'.format(
            self.name,
            self.teacher,
            self.start_date,
            self.end_date,
            self.state
        )

class CourseStudent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.IntegerField(default=0)
    approved = models.BooleanField()

    @property
    def isApproved(self):
        return self.grade > 50

    def __str__(self):
        return '{} ({})'.format(self.student, self.course)

class Attendance(models.Model):
    PRESENT = "P"
    LATE = "L"
    EXCUSED = "E"
    ABSENT = "A"
    ATTENDANCE_CHOICES = [
        (PRESENT, "Present"),
        (LATE, "Late"),
        (EXCUSED, "Excused"),
        (ABSENT, "Absent"),
    ]      
    course_student = models.ForeignKey(CourseStudent, on_delete=models.CASCADE)
    date = models.DateField()
    type = models.CharField(
        max_length = 2,
        choices=ATTENDANCE_CHOICES,
        default = ABSENT
    )

    def __str__(self):
        return '{} - {} ({})'.format(
            self.course_student.student.name,
            self.date,
            self.type
        )

courses/views/view_course.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Teacher, Course

@login_required
def add_course(request):
    if request.method == 'POST':
        name = request.POST['name']
        teacher_id = request.POST['teacher']
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']
        state = request.POST['state']
        material_curso = request.POST['material_curso']

        try:
            teacher = Teacher.objects.get(id=teacher_id)
            course = Course(name=name, teacher=teacher, start_date=start_date,
                            end_date=end_date, state=state, material_curso=material_curso)
            course.save()
            return redirect('courses:index')
        except Exception as e:
            context = {
                'teachers': Teacher.objects.all(),
                'error_message': 'An error occurred while saving the course: {}'.format(str(e))
            }
            return render(request, 'courses/course.html', context)
    else:
        context = {
            'teachers': Teacher.objects.all()
        }
        return render(request, 'courses/course.html', context)

@login_required
def delete_course(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        course.delete()
        return redirect('courses:index')  # Redirect after deletion
    return render(request, 'courses/delete_course.html', {'course': course})    

courses/views/views_courses.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, Http404
from django.utils import timezone
from django.contrib import messages
from ..models import Course, CourseStudent, Attendance
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta

# Create your views here.
@login_required
def index(request):
    courses = get_list_or_404(Course)

    context = {
        'courses': courses
    }

    return render(request, 'courses/index.html', context)

@login_required
def course_detail(request, course_id):
    isOngoingCourse = True
    today = timezone.now().date() ## + timedelta(1)
    course = get_object_or_404(Course, pk=course_id)
    try:
        students = CourseStudent.objects.filter(course=course)       
    except:
        students = [] 

    try:
        attendance_records = Attendance.objects.filter(date=today, course_student__course=course)
        attendance_dict = {record.course_student_id: record for record in attendance_records}
    except Exception as e:
        attendance_dict = {}
        print(f"Error fetching attendance records: {e}")

    # Update students queryset with attendance status
    for student in students:
        student.attendance_today = attendance_dict.get(student.id, None)

    attendance_choices = Attendance.ATTENDANCE_CHOICES

    
    if today > course.end_date:
            isOngoingCourse = False
            messages.error(request, 'No se puede registrar la asistencia fuera de las fechas del curso.')     

    # Get the URL for adding a new student
    add_student_url = reverse('courses:add_course_student', args=[course.id])
    volverUrl = 'http://localhost:8000/courses/'

    context = {
        'course': course,
        'students': students,
        'add_student_url': add_student_url,
        'volverUrl': volverUrl,
        'isOngoingCourse':isOngoingCourse,
        'today':today,
        'attendance_choices': attendance_choices,
    }

    return render(request, 'courses/course_detail.html', context)    

def register_attendance(request, student_id):
    if request.method == "POST":
        try:
            attendance_type = request.POST.get('attendance_type')
            student_course = get_object_or_404(CourseStudent, pk=student_id)

            # Verify if today's date is within the course's start and end dates
            today = timezone.now().date()
            course = student_course.course
            if today < course.start_date or today > course.end_date:
                messages.error(request, 'No se puede registrar la asistencia fuera de las fechas del curso.')
                return redirect('courses:course_detail', course_id=course.id)

            # Create a new attendance record
            Attendance.objects.create(
                course_student=student_course,
                date=today,
                type=attendance_type
            )

            messages.success(request, 'Asistencia registrada correctamente.')
        except Exception as e:
            messages.error(request, f'Error al registrar la asistencia: {str(e)}')

        return redirect('courses:course_detail', course_id=course.id)
    

courses/views/views_coursestudent.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Course, Student, CourseStudent

@login_required
def add_course_student(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    if request.method == 'POST':
        student_id = request.POST['student']
        grade = request.POST['grade']
        approved = grade and int(grade) > 50
        student = get_object_or_404(Student, pk=student_id)
        
        CourseStudent.objects.create(course=course, student=student, grade=grade, approved=approved)
        return redirect('courses:course_detail', course_id=course.id)

    students = Student.objects.exclude(coursestudent__course=course)
    return render(request, 'courses/add_course_student.html', {'course': course, 'students': students})

courses/views/views_students.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from ..models import Student

@login_required
def students(request):
    students = get_list_or_404(Student)

    context = {'students': students}

    return render(request, 'courses/students.html', context)

@login_required
def save_student(request):
    try:
        student = Student(
            name=request.POST['name'],
            ci=request.POST['ci'],
            username=request.POST['username'],
        )
        student.save()
        return redirect('courses:students')
    except Exception:
        students = get_list_or_404(Student)
        context = {
            'students': students,
            'error_message': 'Huvo un error'
        }
        return render(request, 'courses/students.html', context)

courses/views/views_teacher.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from ..models import Teacher

@login_required
def teachers(request):
    try:
        teachers = get_list_or_404(Teacher)
    except:
        teachers = []    

    context = {'teachers': teachers}

    return render(request, 'courses/teacher.html', context)

@login_required
def save_teacher(request):
    try:
        teacher = Teacher(
            name=request.POST['name'],
            ci=request.POST['ci'],
            age=request.POST['age'],
            username=request.POST['username']
        )
        teacher.save()
        return redirect('courses:teacher')
    except Exception:
        teachers = get_list_or_404(Teacher)
        context = {
            'teacher': teachers,
            'error_message': 'Huvo un error'
        }
        return render(request, 'courses/teacher.html', context)

@login_required    
def delete_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    if request.method == 'POST':
        teacher.delete()
        return redirect('courses:teacher')  # Redirect after deletion
    return render(request, 'courses/delete_teacher.html', {'teacher': teacher})     

courses/views/views_user.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout



def login_page(request):
    return render (request, 'courses/login.html', {})

def user_login(request):
    # Check if the user is already logged in
    if request.user.is_authenticated:
        user_name = request.session.get('username')
        user_role = request.session.get('user_role')
        if user_name is not None and user_role is not None:
            return redirect('courses:index')
    
    username = request.POST["username"]
    password = request.POST["password"]
    role = request.POST.get("role")

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)

        # Save username and role in session
        request.session['username'] = username
        request.session['user_role'] = role

        return redirect('courses:index')
    else:
        context = {
            'error_message': 'Nombre de usuario y/o contrasena incorrecto.'
        }
        return render(request, 'courses/login.html', context)
    
def user_logout(request):
    logout(request)
    return redirect('courses:login_page')   

courses/templates/courses/add_course_student.html
{% include 'partials/navbar.html' %}

<h1>Añadir nuevo estudiante al curso "{{ course.name }}"</h1>

<form method="post">
    {% csrf_token %}
    <label for="student">Estudiante:</label>
    <select name="student" id="student">
        {% for student in students %}
            <option value="{{ student.id }}">{{ student.name }} (CI: {{ student.ci }})</option>
        {% endfor %}
    </select>
    <br>
    <label for="grade">Nota:</label>
    <input type="number" name="grade" id="grade" min="0" max="100">
    <br>
    <button type="submit">Añadir estudiante</button>
</form>

courses/templates/courses/course.html
{% include 'partials/navbar.html' %}

<style>
    .button {
      font: bold 11px Arial;
      text-decoration: none;
      background-color: #EEEEEE;
      color: #333333;
      padding: 2px 6px 2px 6px;
      border-top: 1px solid #CCCCCC;
      border-right: 1px solid #333333;
      border-bottom: 1px solid #333333;
      border-left: 1px solid #CCCCCC;
    }
</style>

<h2>Add a New Course</h2>
<form action="{% url 'courses:save_course' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Course Information</legend>
        <label for="name">Course Name:</label>
        <input type="text" name="name" id="name" required>
        <br>
        <label for="teacher">Teacher:</label>
        <select name="teacher" id="teacher" required>
            {% for teacher in teachers %}
                <option value="{{ teacher.id }}">{{ teacher.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date" id="start_date" required>
        <br>
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date" id="end_date" required>
        <br>
        <label for="state">Estado:</label>
        <select name="state" id="state" required>
            <option value="Inactivo">Inactivo</option>
            <option value="Activo" selected>Activo</option>
            <option value="Concluido">Concluido</option>
            <option value="Anulado">Anulado</option>
        </select>
        <br>
        <label for="material_curso">Material del Curso:</label>
        <input type="text" name="material_curso" id="material_curso" required>
        <br>
    </fieldset>
    <input type="submit" value="Add Course">
    <a href="http://localhost:8000/courses/" class="button">Volver</a>
</form>
{% if error_message %}
    <p style="color:red">{{ error_message }}</p>
{% endif %}

courses/templates/courses/course_detail.html
{% include 'partials/navbar.html' %}

<style>
    table {
      border-collapse: collapse;
    }
    tr, td, th { 
      border: solid;
      border-width: 1px;
      padding: 5px;
    }

    .button {
      font: bold 11px Arial;
      text-decoration: none;
      background-color: #EEEEEE;
      color: #333333;
      padding: 2px 6px 2px 6px;
      border-top: 1px solid #CCCCCC;
      border-right: 1px solid #333333;
      border-bottom: 1px solid #333333;
      border-left: 1px solid #CCCCCC;
    }
</style>

<h1>Curso "{{ course.name }}"</h1>
<h2>Lista de estudiantes registrados:</h2>

<!-- <ul>
    {% for cs in students %}
        <li>{{ cs.student.name }} (CI: {{ cs.student.ci }}) - Nota: {{ cs.grade }} - Aprobado: {% if cs.isApproved %}Sí{% else %}No{% endif %}</li>
    {% endfor %}
</ul> -->

<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>CI</th>
            <th>Nota</th>
            <th>Aprobado</th>
            <!-- <th>Acciones</th> -->
            <th>Asistencia {{today}}</th>
        </tr>
    </thead>
    <tbody>
        {% for cs in students %}
        <tr>
            <td>{{ cs.student.name }}</td>
            <td>{{ cs.student.ci }}</td>
            <td>{{ cs.grade }}</td>
            <td>{% if cs.isApproved %}Sí{% else %}No{% endif %}</td>
            <!-- <td>
                <button>Eliminar</button>
                <input type="hidden" name="student_id" value="{{ cs.id }}">
            </td> -->
            <td>
                {% if cs.attendance_today %}
                    <p>{{ cs.attendance_today.get_type_display }}</p>
                {% else %}
                    <form action="{% url 'courses:register_attendance' cs.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <select name="attendance_type">
                            {% for type, description in attendance_choices %}
                            <option value="{{ type }}">{{ description }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit">Registrar Asistencia</button>
                    </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% if isOngoingCourse %}
<a href="{{ add_student_url }}"><button>Añadir nuevo estudiante</button></a>
{% else %}
<!-- <p style="color: red;">El inicio y fin del curso estan fuera del rango de la fecha de hoy {{today}}</p> -->
<p style="color: red;">El curso ya termino. No se puede registrar nuevos estudiantes.</p>
{% endif %}

<a href="{{ volverUrl }}" class="button">Volver</a>

courses/templates/courses/index.html
{% include 'partials/navbar.html' %}

<style>
  .button {
font: bold 11px Arial;
text-decoration: none;
background-color: #EEEEEE;
color: #333333;
padding: 2px 6px 2px 6px;
border-top: 1px solid #CCCCCC;
border-right: 1px solid #333333;
border-bottom: 1px solid #333333;
border-left: 1px solid #CCCCCC;
}
</style>

<h1>Academia - Home</h1>
{% include "courses/lists.html" %}

<div>
  {% if request.session.user_role == "director" or request.session.user_role == "administrador" %}
      <a href="http://localhost:8000/courses/add_course/" class="button">Nuevo Curso</a>
      <a href="http://localhost:8000/courses/student/" class="button">Nuevo Estudiante</a>
      <a href="http://localhost:8000/courses/teacher/" class="button">Nuevo Professor</a>
  {% endif %}
</div>

courses/templates/courses/lists.html
<style>
    table {
      border-collapse: collapse;
    }
    tr, td, th { 
      border: solid;
      border-width: 1px;
      padding: 5px;
    }
</style>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Teacher</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>State</th>
            {% if request.session.user_role == "director" or request.session.user_role == "administrador" %}
            <th>Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        {% if course.id %}
        <tr>
            <td><a href="{% url 'courses:course_detail' course.id %}">{{ course.name }}</a></td>
            <td>{{ course.teacher }}</td>
            <td>{{ course.start_date }}</td>
            <td>{{ course.end_date }}</td>
            <td>{{ course.state }}</td>
            {% if request.session.user_role == "director" or request.session.user_role == "administrador" %}
            <td>

                <form action="{% url 'courses:delete_course' course.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </td>
            {% endif %}
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

courses/templates/courses/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
        }

        .login-container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #333333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
            color: #555555;
        }

        input[type="text"],
        input[type="password"],
        select {
            width: 95%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #cccccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .error-message {
            color: red;
            text-align: center;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>

<div class="login-container">
    <h1>Iniciar Sesión</h1>

    {% if error_message %}
        <div class="error-message">{{ error_message }}</div>
    {% endif %}

    <form action="{% url 'courses:user_login' %}"  method="post">
        {% csrf_token %}
        <label for="role">Rol:</label>
        <select name="role" id="role" required>
            <option value="director">Administrador</option>
            <option value="director">Director</option>
            <option value="profesor">Profesor</option>
            <option value="estudiante" selected>Estudiante</option>
        </select>
        <label for="username">Nombre de Usuario:</label>
        <input type="text" name="username" id="username" required>

        <label for="password">Contraseña:</label>
        <input type="password" name="password" id="password" required>

        <button type="submit">Iniciar Sesión</button>
    </form>
</div>

</body>
</html>

courses/templates/courses/students.html
{% include 'partials/navbar.html' %}

<style>
    table {
      border-collapse: collapse;
    }
    tr, td, th { 
      border: solid;
      border-width: 1px;
      padding: 5px;
    }

    .button {
      font: bold 11px Arial;
      text-decoration: none;
      background-color: #EEEEEE;
      color: #333333;
      padding: 2px 6px 2px 6px;
      border-top: 1px solid #CCCCCC;
      border-right: 1px solid #333333;
      border-bottom: 1px solid #333333;
      border-left: 1px solid #CCCCCC;
    }
</style>

<h1>Estudiantes</h1>

<form action="{% url 'courses:save_student' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h2>Registro de Estudiantes</h2></legend>
        {% if error_message %}<p><string>{{ error_message }}</string></p>{% endif %}
        <label for="name">Nombre</label><input type="text" name="name" id="name"/>
        <br>
        <label for="username">Nombre de usuario</label><input type="text" name="username" id="username" required/>
        <br>
        <label for="ci">CI</label><input type="text" name="ci" id="ci"/>
    </fieldset>
    <input type="submit" value="Registrar"/>
    <a href="http://localhost:8000/courses/" class="button">Volver</a>
</form>

<h2>Lista de Estudiantes</h2>
<ul>
    {% for student in students %}
    <li>{{ student.name }} - {{ student.ci }}</li>
    {% endfor%}
</ul>

courses/templates/courses/teacher.html
{% include 'partials/navbar.html' %}

<style>
    table {
      border-collapse: collapse;
    }
    tr, td, th { 
      border: solid;
      border-width: 1px;
      padding: 5px;
    }

    .button {
      font: bold 11px Arial;
      text-decoration: none;
      background-color: #EEEEEE;
      color: #333333;
      padding: 2px 6px 2px 6px;
      border-top: 1px solid #CCCCCC;
      border-right: 1px solid #333333;
      border-bottom: 1px solid #333333;
      border-left: 1px solid #CCCCCC;
    }
</style>

<h1>Teacher</h1>
<form action="{% url 'courses:save_teacher' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h2>Registro de Teachers</h2></legend>
        {% if error_message %}<p><string>{{ error_message }}</string></p>{% endif %}
        <label for="name">Nombre</label><input type="text" name="name" id="name" required/>
        <br>
        <label for="username">Nombre de usuario</label><input type="text" name="username" id="username" required/>
        <br>
        <label for="ci">CI</label><input type="text" name="ci" id="ci" required/>
        <br>
        <label for="ci">Age</label><input type="text" name="age" id="age" required/>
    </fieldset>
    <br>
    <input type="submit" value="Registrar"/>
    <a href="http://localhost:8000/courses/" class="button">Volver</a>
</form>

<!-- <h2>Lista de Teachers</h2>
<ul>
    {% for teacher in teachers %}
    <li>{{teacher.username}}  - {{ teacher.name }} - {{teacher.ci}} - {{teacher.age}}</li>
    {% endfor%}
</ul> -->

<br>
<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Name</th>
            <th>CI </th>
            <th>Age</th>
            {% if request.session.user_role == "director" or request.session.user_role == "administrador" %}
            <th>Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for teacher in teachers%}
        <tr>
            <td>{{ teacher.username }}</td>
            <td>{{ teacher.name }}</td>
            <td>{{ teacher.ci }}</td>
            <td>{{ teacher.age}}</td>
            {% if request.session.user_role == "director" or request.session.user_role == "administrador" %}
            <td>
                <form action="{% url 'courses:delete_teacher' teacher.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>